### ISSUE TITLE
pytest >= 8.2 is not yet supported (not only tests fail)

### ISSUE THREAD

**Issue by icemac** [pytest-dev/pytest-rerunfailures#267]
See https://github.com/pytest-dev/pytest-rerunfailures/actions/runs/8409152908/job/23026172136

This ~~can be a temporary problem or a~~ is a hint that we have to change something here to make it compatible again.

**Comment by mgorny** [comment]
This is now affecting pytest 8.2.0.

**Comment by Chris-Peterson444** [comment]
This looks like a repeat of what https://github.com/pytest-dev/pytest-rerunfailures/commit/0ab54f00d68bb4feadae58d2f4e30f6663495571 tried to address (the teardown fixtures are not being called correctly). I spent some time debugging this this afternoon and the logic still looks correct, although it is effectively the same error. I'm not too familiar with the pytest internals but I wonder if the fix is somewhere along the lines of keeping a reference to the original setupstate instead of the depending on the final tests setupstate object?

**Comment by dkuchynskyi** [comment]
Hi guys, I think we've faced the same problem using pytest-rerunfailures with pytest 8.2.2 and pytest-xdist 3.6.1. we run tests with xdist loadscope and rerunfailures and on the step of collecting tests it fails:

```
platform linux
pytest-8.2.2
configfile: pytest.ini
plugins: rerunfailures-14.0, xdist-3.6.1
created: 3/3 workers
3 workers [43 items]

scheduling tests via LoadScopeScheduling
INTERNALERROR> def worker_internal_error(
INTERNALERROR>         self, node: WorkerController, formatted_error: str
INTERNALERROR>     ) -> None:
INTERNALERROR>         """
INTERNALERROR>         pytest_internalerror() was called on the worker.
INTERNALERROR>     
INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
INTERNALERROR>         here ourselves using the formatted message.
INTERNALERROR>         """
INTERNALERROR>         self._active_nodes.remove(node)
INTERNALERROR>         try:
INTERNALERROR> >           assert False, formatted_error
```

We had to rollback to pytest 7.4.4 but left rerunfailures-14.0, xdist-3.6.1 and now it works properly.
Could you look at it please
thanks

**Comment by mkmoisen** [comment]
With pytest==8.2.2 and pytest-xdist==3.6.1, and pytest-rerunfailures==14.0, all tests that undergo a rerun result in the following AssertionError:

```
    def runtest(self) -> None:
        from _pytest.debugging import maybe_wrap_pytest_function_for_tracing
    
        testcase = self.instance
>       assert testcase is not None
E       AssertionError
```

It works fine for me on pytest==8.2.1 and pytest-cdist==3.5.0 and pytest-rerunfailures==14.0.

**Comment by SachinKSingh28** [comment]
It seems reruns are not working with pytest==8.2.2 and pytest-rerunfailures==14.0, anyone aware of any workarounds?

**Comment by icemac** [comment]
The currently only known workaround is to use an older version of `pytest`.

**Comment by jakkdl** [comment]
@asottile-sentry had [teardown issues and bisected it](https://github.com/pytest-dev/pytest/pull/11833#issuecomment-2356711497) to https://github.com/pytest-dev/pytest/pull/11833 (which I authored). https://github.com/pytest-dev/pytest/issues/12135 could also be the cause of some of the errors.

I'm not familiar with how pytest-rerunfailures messes with teardowns, but maybe looking through those PRs can help you debug.

**Comment by filiplajszczak** [comment]
Thanks @jakkdl I can confirm that pytest-dev/pytest@70c11582aaed is the exact commit that causes the fail of five tests in pytest-rerunfailures test suite:

* `test_run_session_teardown_once_after_reruns`
* `test_exception_matches_rerun_except_query`
* `test_exception_not_match_rerun_except_query`
* `test_exception_matches_only_rerun_query`
* `test_exception_match_only_rerun_in_dual_query`

**Comment by jakkdl** [comment]
reopening this as pytest==8.2 is still broken: https://github.com/pytest-dev/pytest-rerunfailures/pull/278#issuecomment-2457500621

**Comment by asottile-sentry** [comment]
it looks like this was fixed in 8.2.x after 8.2.2 regressed but 8.2.3 was never released -- I believe you can use `!=8.2.2` and 8.2.1 should work (and in theory if https://github.com/pytest-dev/pytest/pull/12438 is ever released then it will "just work" in 8.2.3 -- cc @nicoddemus @bluetech )

**Comment by icemac** [comment]
A fix for this issue is released in https://pypi.org/project/pytest-rerunfailures/15.0/.
Thank you to all how helped fixing this issue.

**Comment by asottile-sentry** [comment]
so weirdly enough we're still seeing the same symptoms (likely a teardown missing soon after a flake causing a cascading failure) with 15.x and pytest 8.3.3 -- haven't been able to narrow down a reproducible failure yet but will keep you in the loop if I find something

**Comment by jakkdl** [comment]
> so weirdly enough we're still seeing the same symptoms (likely a teardown missing soon after a flake causing a cascading failure) with 15.x and pytest 8.3.3 -- haven't been able to narrow down a reproducible failure yet but will keep you in the loop if I find something

I'm not super shocked if my PR to rerunfailures was insufficient; esp if xdist is involved

**Comment by chaporgin** [comment]
Should this issue be reopened, then? Still seeing similar failures as above:

> with 15.x and pytest 8.3.3

**Comment by jakkdl** [comment]
> Should this issue be reopened, then? Still seeing similar failures as above:
> 
> > with 15.x and pytest 8.3.3

could you provide a repro?

**Comment by henzef** [comment]
I also saw this issue with pytest 8.4.1 and pytest-rerunfailures 15.1. Unfortunately it doesnt seem reproducable :(

**Comment by icemac** [comment]
Fixed long time ago.
